omrails2/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'attenders' => 'users#index'
  get 'classes' => 'discipleship_classes#index'

  resources :discipleship_classes
  resources :users
end

omrails2/app/models/discipleship_class.rb
class DiscipleshipClass < ActiveRecord::Base
	has_many :users
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
end

omrails2/app/models/user.rb
class User < ActiveRecord::Base
	has_many :discipleship_classes
end

omrails2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

omrails2/app/controllers/discipleship_classes_controller.rb
class DiscipleshipClassesController < ApplicationController
  before_action :set_discipleship_class, only: [:show, :edit, :update, :destroy]

  # GET /discipleship_classes
  # GET /discipleship_classes.json
  def index
    @discipleship_classes = DiscipleshipClass.all
  end

  # GET /discipleship_classes/1
  # GET /discipleship_classes/1.json
  def show

  end

  # GET /discipleship_classes/new
  def new
    @discipleship_class = DiscipleshipClass.new
  end

  # GET /discipleship_classes/1/edit
  def edit
  end

  # POST /discipleship_classes
  # POST /discipleship_classes.json
  def create
    @discipleship_class = DiscipleshipClass.new(discipleship_class_params)

    respond_to do |format|
      if @discipleship_class.save
        format.html { redirect_to @discipleship_class, notice: 'Discipleship class was successfully created.' }
        format.json { render :show, status: :created, location: @discipleship_class }
      else
        format.html { render :new }
        format.json { render json: @discipleship_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discipleship_classes/1
  # PATCH/PUT /discipleship_classes/1.json
  def update
    respond_to do |format|
      if @discipleship_class.update(discipleship_class_params)
        format.html { redirect_to @discipleship_class, notice: 'Discipleship class was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipleship_class }
      else
        format.html { render :edit }
        format.json { render json: @discipleship_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discipleship_classes/1
  # DELETE /discipleship_classes/1.json
  def destroy
    @discipleship_class.destroy
    respond_to do |format|
      format.html { redirect_to discipleship_classes_url, notice: 'Discipleship class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipleship_class
      @discipleship_class = DiscipleshipClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipleship_class_params
      params.require(:discipleship_class).permit(:class_date, :title, :user_id)
    end
end

omrails2/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

omrails2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @discipleship_classes = @user.discipleship_classes.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :children, :mom, :dad)
    end
end

omrails2/app/helpers/application_helper.rb
module ApplicationHelper
end

omrails2/app/helpers/discipleship_classes_helper.rb
module DiscipleshipClassesHelper
end

omrails2/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

omrails2/app/helpers/users_helper.rb
module UsersHelper
end

omrails2/app/views/discipleship_classes/_discipleship_class.html.erb
<li id="discipleship_class-<%= discipleship_class.id %>">
 
  <span class="content"><%= link_to discipleship_class.title, discipleship_class %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(discipleship_class.created_at) %> ago.
  </span>
</li>

omrails2/app/views/discipleship_classes/_form.html.erb
        <%= form_for(@discipleship_class, html: {class: 'form-horizontal'}) do |f| %>
        <% if @discipleship_class.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@discipleship_class.errors.count, "error") %> prohibited this discipleship_class from being saved:</h2>

            <ul>
            <% @discipleship_class.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field form-group">
          <%= f.label :class_date, class: 'col-sm-2 control-label'  %>
          <div class="col-sm-5">
          <%= f.date_select :class_date, class: 'form-control' %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :title, class: 'col-sm-2 control-label'  %>
          <div class="col-sm-5">
          <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
        <div class="field form-group">
          <%= f.label :user_id, class: 'col-sm-2 control-label'  %>
          <div class="col-sm-5">
          <%= f.text_field :user_id, class: 'form-control' %>
          </div>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
      

omrails2/app/views/discipleship_classes/edit.html.erb
<h1>Editing Discipleship Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @discipleship_class %> |
<%= link_to 'Back', discipleship_classes_path %>

omrails2/app/views/discipleship_classes/index.html.erb
<p id="notice"><%= notice %></p>

<div id="main-container" class="container-fluid">
  <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><span class="sr-only">(current)</span><%= link_to "All Classes", classes_path %></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
        </div>
        <div id="main-content" class="col-xs-9">
            <h1>Discipleship Classes</h1>
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Class date</th>
                  <th>Title</th>
                  <th colspan="3" style="text-align:center">Options</th>
                </tr>
              </thead>

              <tbody>
                <% @discipleship_classes.each do |discipleship_class| %>
                  <tr>
                    <td><%= discipleship_class.class_date %></td>
                    <td><%= discipleship_class.title %></td>
                    <td><%= link_to 'Show', discipleship_class %></td>
                    <td><%= link_to 'Edit', edit_discipleship_class_path(discipleship_class) %></td>
                    <td><%= link_to 'Delete', discipleship_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= link_to 'Add New Discipleship Class', new_discipleship_class_path,  class: 'btn btn-success'%>
        </div>
      </div>
    </div>

omrails2/app/views/discipleship_classes/new.html.erb
<div id="main-container" class="container-fluid">
  <div class="row">
	    <div id="sidebar" class="col-xs-2">
	    <h3>Sidebar</h3>
	    </div>
	    <h1>Add Discipleship Class</h1>
	    <div id="main-content" class="col-xs-10">
				<%= render 'form', role: 'form' %>

				<%= link_to 'Back', discipleship_classes_path %>
		</div>
	</div>
</div>

omrails2/app/views/discipleship_classes/show.html.erb
<div id="main-container" style="text-align:left;" class="container-fluid">
	<div class="row">
	    <div class="col-sm-3 col-md-2 sidebar">
	      <ul class="nav nav-sidebar">
	        <li class="active"><span class="sr-only">(current)</span><%= link_to "All Attenders", attenders_path %></li>
	        <li><a href="#">Reports</a></li>
	        <li><a href="#">Analytics</a></li>
	        <li><a href="#">Export</a></li>
	      </ul>
	    </div>
	    <div id="main-content" class="col-xs-10">
			<p id="notice"><%= notice %></p>
			<p>
			  <strong>Class date:</strong>
			  <%= @discipleship_class.class_date %>
			</p>
			<p>
			  <strong>Title:</strong>
			  <%= @discipleship_class.title %>
			</p>
			<p>
			  <strong>ID:</strong>
			  <%= @discipleship_class.user_id %>
			</p>




			<%= link_to 'Edit', edit_discipleship_class_path(@discipleship_class), class: 'btn btn-default' %> |
			<%= link_to 'Back', discipleship_classes_path, class: 'btn btn-default' %>
		</div>
	</div>
</div>

omrails2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omrails2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navigation' %>
<%= yield %>

</body>
</html>

omrails2/app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag "monroe_logo-single-color.png" %></a>
      <nav>
          <ul class="nav navbar-nav navbar-right" style="padding-top:15px;">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "List Attenders", attenders_path %></li>
            <li><%= link_to "List Classes", classes_path %></li>
            <li><%= link_to "Help",   help_path %></li>
          </ul>
       </nav>
  </div>
</nav>

omrails2/app/views/static_pages/help.html.erb
 <div class="starter-template">

        <div class="jumbotron">
            <h1>Help</h1>
	        <p class="lead">A collection of tips to help you navigate and use the Attender Database</p>  
        </div>
        
        <h4>What is the Attender Database?</h4>
	        <p>Every attender of Monroe Church of the Nazarene is on a journey where the destination is a deep and active relationship with Christ.  This database helps the leadership know more about each attender and have the information they need to disciple them on their journey.</p>
      </div>

omrails2/app/views/static_pages/home.html.erb
<body>
	<div class="site-wrapper">
		<div class="site-wrapper-inner">
			 <div class="cover-container">

				  <div class="inner cover">
				            <h1 class="cover-heading">A Better Way to Disciple</h1>
				            <p class="lead">Know more about our Church family.</p>
				            
				  </div>

      <div class="row">
        <div class="col-lg-4">
          <%= image_tag "worship_circle.png" %>
          <h2>Attenders</h2>
          <p>View church attender profiles</p>
          <p><%= link_to "View Attenders", attenders_path, class: 'btn btn-default' %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag "classes_circle.png" %>
          <h2>Classes</h2>
          <p>Review discipleship class details</p>
          <p><%= link_to "View Classes", classes_path, class: 'btn btn-default' %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag "teacher_circle.png" %>
          <h2>Teachers</h2>
          <p>Review teacher profiles</p>
          <p><a class="btn btn-default" href="#" role="button">Coming Soon &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


		<div class="mastfoot">
            <div class="inner">
              <p>Monroe Church of the Nazarene</p>
            </div>
        </div>
		      
			</div>
		</div>
	</div>
</body>

omrails2/app/views/users/_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label 'First Name', class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.text_field :first_name, class: 'form-control' %>
    </div>
  </div>
   <div class="field form-group">
    <%= f.label 'Last Name', class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.text_field :last_name, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :email , class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.text_field :email , class: 'form-control'%>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :phone, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :children, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.text_field :children, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :mom, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.text_field :mom, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :dad, class: 'col-sm-2 control-label' %>
    <div class="col-sm-5">
    <%= f.text_field :dad, class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

omrails2/app/views/users/_user_list.html.erb
<li id="user-<%= user.id %>">
 
  <span class="user-name"><%= link_to user.title, user %></span>
</li>

omrails2/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

omrails2/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div id="main-container" class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><span class="sr-only">(current)</span><%= link_to "All Attenders", attenders_path %></li>
        <li><a href="#">Reports</a></li>
        <li><a href="#">Analytics</a></li>
        <li><a href="#">Export</a></li>
      </ul>
    </div>
    <div id="main-content" class="col-xs-10" style="text-align:left;">

        <h1>Monroe Nazarene Attenders</h1>
        <%= will_paginate %>

        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Children</th>
              <th>Mom</th>
              <th>Dad</th>
              
              <th colspan="3" style="text-align:center">Options</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= user.phone %></td>
                <td><%= user.children %></td>
                <td><%= user.mom %></td>
                <td><%= user.dad %></td>
                
                <td><%= link_to 'Show', user %></td>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <p><%= link_to 'Add Another Attender', new_user_path, class: 'btn btn-success' %></p>
        <%= will_paginate %>
  </div>
</div>
</div>

omrails2/app/views/users/new.html.erb
<div id="main-container" class="container-fluid">
  <div class="row">
	    <div id="sidebar" class="col-xs-2">
	    <h3>Sidebar</h3>
	    </div>
		<div id="main-content" class="col-xs-10">
			<h1>Add Another Attender</h1>
			<br>
			<%= render 'form' %>

			<%= link_to 'Back', users_path %>
		</div>
	</div>
</div>

omrails2/app/views/users/show.html.erb
<div id="main-container" style="text-align:left;" class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar"><br>

        <li><strong>Quick Stats</strong></li>
        <li>Classes Attended: <%= @user.discipleship_classes.count %></li>
      </ul>
    </div>
    <div id="main-content" class="col-xs-10">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>First Name:</strong>
        <%= @user.first_name %>
      </p>

      <p>
        <strong>Last Name:</strong>
        <%= @user.last_name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @user.phone %>
      </p>

      <p>
        <strong>Children:</strong>
        <%= @user.children %>
      </p>

      <p>
        <strong>Mom:</strong>
        <%= @user.mom %>
      </p>

      <p>
        <strong>Dad:</strong>
        <%= @user.dad %>
      </p>
    <% if @user.discipleship_classes.any? %>
      <h3>Discipleship Classes </h3>
      <ol class="classes">
        <%= render @discipleship_classes %>
      </ol>
      <%= will_paginate @discipleship_classes %>
    <% end %>

      <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default' %> |
      <%= link_to 'Back', users_path, class: 'btn btn-default' %>

  </div>
</div>